### PR TITLE
Output values of channel 1 and 2 to file

### PR DESCRIPTION
**Pull request by mzaffalon**

### CODE REVIEW

**Comment by mzaffalon** [comment]
I find it more useful to output to file instead of stdout. In this way I could see that write and read operations in the M2K are not synchronous.

**Comment by AlexandraTrifan** [comment]
The examples are provided for guidance on how to use the libm2k API. Writing the acquired data to file is beyond the purpose of this example. 
The user can implement any preferred way to manipulate the data (whether it's written directly to a file, redirected from the console or any other way).

**Comment by mzaffalon** [comment]
Currently, the data is output to console, which is in my opinion not more useful then writing it to file.

**Comment by rgetz** [comment]
Data bring output to console- is sort of the "Unix way". https://en.m.wikipedia.org/wiki/Unix_philosophy

That way if can be piped into any tool you want. 

- Robin

**Pull request closed without merging**
